### ISSUE TITLE
Unable to connect from android device to laptop via webrtc

### ISSUE THREAD

**Issue by sushantt2099** [cjb/serverless-webrtc#13]
I am trying establish webrtc session between android device and laptop over wifi(does not have access to internet) using chrome browser.

Connection never get establish after exchanging the webrtc offer and answer between android and laptop.

But it works on firefox.

**Comment by infinity0** [comment]
Could you provide some more details for debugging? Have you tried filing an issue to Chrome? It may be that this is a Chrome issue, not a serverless-webrtc issue.

**Comment by sushantt2099** [comment]
more details can be found here http://stackoverflow.com/questions/29153884/unable-to-connect-from-android-device-to-laptop-via-webrtc

I have filled the same issue with the webrtc project here https://code.google.com/p/webrtc/issues/detail?id=4457 
looks like its chrome specific issue.

**Comment by sushantt2099** [comment]
Hi, can you help me resolve this issue. 
https://code.google.com/p/webrtc/issues/detail?id=4457
people at webrtc is saying serverless-webrtc might have bug in it.
