### ISSUE TITLE
Not working in Firefox 38

### ISSUE THREAD

**Issue by pattyland** [cjb/serverless-webrtc#14]
> TypeError: Not enough arguments to mozRTCPeerConnection.setLocalDescription.
> pc1.setLocalDescription(desc, function () {});

**Comment by Samardon** [comment]
Looks like the demo just needs to be updated to the latest version.
Master branch works fine when tested.

**Comment by cjb** [comment]
@Samardon Very belated thanks for figuring that out!  Updated the demo link to master.
