### ISSUE TITLE
How would you build other clients?

### ISSUE THREAD

**Issue by whatisgravity** [cjb/serverless-webrtc#19]
Sorry if this is out of the scope of this project but if I wanted to build say a C++ client using QT to connect to peers in their browser, how do I connect to the peers? What is the nodejs native client leveraging to be able to do that?

**Comment by whatisgravity** [comment]
It appears it uses webrtc which uses: https://github.com/js-platform/libwebrtc

**Comment by infinity0** [comment]
@whatisgravity that repo seems way out of date. in keroserene/go-webrtc#10 we have been trying to figure out a way to build (and eventually persuade google upstream to maintain) a `libjingle_peerconnection.so`, you can read through that for details.

**Comment by whatisgravity** [comment]
Wow thank you for pointing me in the right direction. I sent you an email regarding the project since I noticed you forked it.
