### ISSUE TITLE
using STUN?

### ISSUE THREAD

**Issue by colinsullivan** [cjb/serverless-webrtc#20]
I wonder if I am missing something, aren't you using Google's signaling server here?

https://github.com/cjb/serverless-webrtc/blob/master/serverless-webrtc.js#L25

**Comment by colinsullivan** [comment]
ah I see the difference now :palm_tree:

I did not understand the ICE constraint for WebRTC in the context of "serverless".

**Comment by cjb** [comment]
Yeah :) If someone happens to be in an environment where both participants aren't using NAT, they could disable the STUN server.  But most people won't be.
