### ISSUE TITLE
Text only version?

### ISSUE THREAD

**Issue by RaedsLab** [cjb/serverless-webrtc#22]
I'm working on a _text-only_ fork of this project. 
Is there a way to create an offer without a stream object?

**Comment by cjb** [comment]
This project was actually text only until recently, so you can just revert the latest commits, assuming I understand what you mean.

**Comment by RaedsLab** [comment]
Thanks I didn't think to check in the commit history.
This should be e7088b39b03d3bfc485599a6d9f020410e29c888  right ?

**Comment by cjb** [comment]
Yup.
