### ISSUE TITLE
potential XSS in chat log

### ISSUE THREAD

**Issue by diracdeltas** [cjb/serverless-webrtc#41]
i wasn't able to test this because the demo is broken, but https://github.com/cjb/serverless-webrtc/blob/master/js/serverless-webrtc.js#L314 injects messages as HTML without escaping. so if alice sends `<script>alert('hi')</script>` to bob in the chat log, it may get executed in bob's browser (https://github.com/cjb/serverless-webrtc/blob/master/js/serverless-webrtc.js#L146)

**Comment by cjb** [comment]
@diracdeltas I can confirm the XSS worked :)  Thanks for the report, fixed now!
